# Generated by Django 5.0 on 2025-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
