# Generated by Django 5.0 on 2025-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_profile_show_email_profile_show_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_Recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
