# Generated by Django 5.0 on 2025-09-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_experience_application_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
    ]
