# Generated by Django 5.0 on 2025-10-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
